version: "3.8"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=cleanarch-poc-local
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro

volumes:
  postgres:
    driver: local
